question_data = [{"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "Grand Theft Auto V is the fifteenth installment of the Grand Theft Auto series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "McCree from Overwatch originally started as a character that was going to appear in a scrapped Starcraft game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In the video game &quot;Blue Reflection&quot;, the main protagonist, Hinako Shirai, was a ballet dancer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Rollercoaster Tycoon 1 and 2 were developed by Chris Sawyer.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the Super Mario series, the character Pauline is a Princess like Princess Peach.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In Riot Games &quot;League of Legends&quot; the name of Halloween event is called &quot;The Reckoning&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Team Fortress 2, the weapon &quot;Your Eternal Reward&quot; is a reference to the 1992 film Aladdin.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "The video game &quot;Fuel&quot; has an open world that is 5,560 square miles?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "Fortnite was originally intended to be a horror game.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "As of February 2019, the &quot;Donkey Kong Country&quot; series only had released five games (not counting remakes or ports).",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "The Paradox Interactive game &quot;Stellaris&quot; was released in 2016.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "The Ace Attorney trilogy was suppose to end with &quot;Phoenix Wright: Ace Attorney &minus; Trials and Tribulations&quot; as its final game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "Pistons were added to Minecraft in Beta 1.5.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Donkey Kong was originally set to be a Popeye arcade game.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "There are 2 player roles in Trouble in Terrorist Town.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Pokemon, Bulbasaur is the only starter pokemon that is a Grass\\Poison type.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "&quot;Half-Life 2&quot; runs on the Source Engine.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Terraria, you can craft the Cell Phone pre-hardmode.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In &quot;Tony Hawk&#039;s Underground&quot;, the main character&#039;s friend turned rival is named &quot;Jeff Sampson&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "The first Maxis game to feature the fictional language &quot;Simlish&quot; was The Sims (2000).",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "In the game Nuclear Throne, the boss &quot;Big Dog&quot; was made into a character on April Fool&#039;s Day 2015.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In &quot;Mother 3,&quot; the bird on the Ultimate Chimera&#039;s head is there only for decoration.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the game &quot;Destiny,&quot; the three subclasses of the Hunter are Bladedancer, Nightstalker, and Sunsinger.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In the game &quot;Subnautica&quot;, a &quot;Cave Crawler&quot; will attack you.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
